version: "3"

services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306 # cannot change this port to other number
      - MYSQL_DATABASE=tesla # name you want for the database
      - MYSQL_USER=tesla # change to whatever username you want
      - MYSQL_PASSWORD=123456 #change to the password you want for user
      - MYSQL_ROOT_PASSWORD=123456 #change to good root password
    ports:
      - "3307:3306"

  dolt:
    build: .
    entrypoint: dolt
    command: sql-server -H 0.0.0.0
    volumes:
      - .:/tesla
    ports:
      - "3306:3306"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - dolt
      - mysql
