# Generated by Django 3.1.7 on 2021-04-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210407_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='adj_close',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
