# Generated by Django 3.1.7 on 2021-04-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210407_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('timestamp', models.TextField(null=True)),
                ('ipfs_mirror_url', models.TextField(null=True)),
                ('type', models.CharField(choices=[('website', 'Website'), ('video', 'Video'), ('audio', 'Audio')], max_length=32)),
            ],
            options={
                'db_table': 'information_source',
            },
        ),
        migrations.CreateModel(
            name='DeliveriesGlobalByQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], max_length=4)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('models', models.TextField()),
                ('units', models.IntegerField()),
                ('information_source', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.informationsource')),
            ],
            options={
                'db_table': 'deliveries__global_by_quarter',
                'ordering': ('year', 'quarter', 'models'),
                'unique_together': {('year', 'quarter', 'models')},
            },
        ),
    ]
