# Generated by Django 3.1.7 on 2021-04-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_deliveriesglobalbyquarter_informationsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationsource',
            name='ipfs_mirror_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='informationsource',
            name='timestamp',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
